version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: q-orm-postgres
    environment:
      POSTGRES_DB: qorm
      POSTGRES_USER: qorm
      POSTGRES_PASSWORD: qorm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all -c log_destination=stderr

volumes:
  postgres_data: